FINALPACKAGE = 1
DEBUG = 0

ARCHS = armv7 armv7s arm64 arm64e
THEOS_DEVICE_IP = 192.168.0.87
include $(THEOS)/makefiles/common.mk

TOOL_NAME = LimeHelper
LimeHelper_FILES = main.mm

include $(THEOS_MAKE_PATH)/tool.mk
